server:
  port: 8080
spring:
  profiles:
    active:
    include: secret
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: gkdlfn12
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  genFileDirPath: /Users/parkchang-gyu/Desktop/img_upload
  resourcePath: file:///Users/parkchang-gyu/Desktop/img_upload/
  requestPath: /img_upload/**
  originPath: /img_upload/